name: Package UMTK UI

on:
  workflow_dispatch:
    inputs:
      dummy:
        description: "Dummy"
        type: string
        required: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Do nothing
        run: |
          echo "Building UMTK UI..."